url: "https://scho249.github.io"
baseurl: ""

# Site settings
title: Claire Cho
email: seovo351@gmail.com
description: "Comprehensive data science related projects"



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: LinkedIn
    url: "https://www.linkedin.com/in/seoyoung-cho-a669721a9/"
  - title: github
    url: "https://github.com/scho249"

# Postal address (add as many lines as necessary)
address:
  - line: Mountlake Terrace, WA 98043

# Build settings
markdown: kramdown
permalink: pretty
